openapi: 3.0.0

info:
  title: Recht API
  description: Recht administratie service
  version: "1.0"

servers:
  - url: http://localhost:8080
    description: "Development server"

tags:
  - name: Annuity
    description: Annuity REST API

security:
  - BearerAuth: [ ]

paths:
  /repayment-schedule:
    post:
      operationId: getRepaymentSchedule
      summary: Get repayment schedule for a given loan.
      description: "Get repayment schedule for a given loan."
      tags:
        - Annuity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: Loan
      responses:
        '200':
          description: The repayment schedule of the loan
          content:
            application/json:
              schema:
                type: RepaymentSchedule
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerError'
components:
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ServerError:
      description: Server side problem
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    Loan:
      type: object
      title: Loan
      description: The loan
      required:
        - initialLoan
        - annualInterestPercentage
        - periodicity
        - startDate
        - timing
        - loanTermInMonths
      properties:
        initialLoan:
          type: number
          description: The initial loan
        annualInterestPercentage:
          type: number
          description: The annual interest percentage
        startDate:
          type: string
          format: date
          description: The start date of the loan
        endDate:
          type: string
          format: date
          description: The end date of the loan
        loanTermInMonths:
          type: integer
          description: Test
        periodicity:
          type: Periodicity
        timing:
          type: Timing
    LoanStatement:
      type: object
      title: LoanStatement
      description: A loan statement
      properties:
        period:
          type: integer
          description: Period number of the loan statement
        date:
          type: string
          format: date
          description: The date of the loan statement
        balance:
          type: number
          description: The balance of the loan after payment
        payment:
          type: Payment
        totalInterest:
          type: number
          description: Total interest after payment
    Payment:
      type: object
      title: Payment
      description: A payment
      properties:
        totalPayment:
          type: number
          description: The total payment
        interestAmount:
          type: number
          description: The interest amount of the payment
        repaymentAmount:
          type: number
          description: The repayment amount of the payment
    RepaymentSchedule:
      type: object
      title: Repayment schedule
      description: The repayment schedule of the loan
      properties:
        loan:
          type: Loan
          description: The loan
        loanStatements:
          type: array
          items:
            $ref: '#/components/schemas/LoanStatement'

    ErrorResponse:
      type: object
      title: Error response
      description: Error response attributes
      properties:
        reason:
          type: string
          description: Message
        reference:
          type: string
          format: uuid
          description: Reference UUID